### ISSUE TITLE
Analyze returning no results due to seemingly broken filter values

### ISSUE THREAD

**Issue by breyer** [elsbrock/hetzner-radar#49] opened 2024-10-09 18:07 UTC
This wonderful website delivers currently no results.

**Comment by elsbrock** [comment] 2024-10-10 09:21
You closed it, I assume it's working again for you? I couldn't reproduce.

**Comment by breyer** [comment] 2024-10-10 21:19
The page did not return any results at times. Reloading the page several times did not help. Later it worked again.

**Comment by elsbrock** [comment] 2024-10-11 07:53
I have seen it yesterday too. Will try to figure it out. Thanks for bringing this up.

**Comment by PureFallen** [comment] 2024-10-14 17:50
I stumbled over the same issue when trying to use the website and assume that it might be related to incorrect/incomplete/duplicate saving of information in the URL (GET Parameters) that lead to the settings having impossible videos.

Trying to open the website once for example caused this URL to be generated:
https://radar.iodev.org/analyze#cpuAMD=true&cpuCount=1&cpuIntel=true&extrasGPU=false&extrasHWR=false&extrasRPS=false&hddCount[]=3&hddCount[]=2&hddInternalSize[]=24&hddInternalSize[]=16&locationFinland=true&locationGermany=true&ramInternalSize[]=7&ramInternalSize[]=6&recentlySeen=false&ssdNvmeCount[]=4&ssdNvmeCount[]=0&ssdNvmeInternalSize[]=10&ssdNvmeInternalSize[]=12&ssdSataCount[]=2&ssdSataCount[]=0&ssdSataInternalSize[]=8&ssdSataInternalSize[]=4

This causes a lot of settings to be broken such as "at least 128 GB of Memory, but no more than 64 GB of Memory" which is not possible.

Whenever I run into the issue right now the solution for me is usually just to clean the URL, forcing him to send me straight to https://radar.iodev.org/analyze and from there setting all settings by hand again... Not optimal but at least one can work with that.

**Closed** 2024-10-20 17:47 UTC
